server:
  port: 8089
  servlet:
    context-path: /clientSystem
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sweb?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
security:
  oauth2:
    client:
      client-id: test
      client-secret: client
      access-token-uri: http://localhost:8088/oauth/token
      user-authorization-uri: http://localhost:8088/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8088/oauth/token_key
